### ISSUE TITLE
enable empty text search

### ISSUE THREAD

**Issue by anjali9791** [goto/compass#58]
We should enable empty text search, currently if no search keywords are provided we send an error.

**Comment by haveiss** [comment]
Can you give a bit detail why we need this? and why we couldn't use the GetAllAssets API? 
We have similar discussion here https://github.com/raystack/compass/issues/201

**Comment by anjali9791** [comment]
Based on last discussion we aligned on using one api and slowly deprecate GetAllAssets. 
You can check the discussion here : https://github.com/goto/compass/pull/49.
